Task swe 1170 create day select
senseteq-io/senseteq-booking-module pull request #30
Opened 2022-07-19 14:43 UTC by whoiam460

2022-07-19 14:51 UTC, aleksandrgolyk approved these changes

2022-07-19 14:53 UTC, olenashevchuk commented on src/app/components/elements/DaySelect/DaySelect.js
> +                <DayView
use {...item}

2022-07-19 15:07 UTC, GingerBoy14 requested changes

2022-07-19 16:25 UTC, 5P4C3GR33D approved these changes

2022-07-20 08:10 UTC, olenashevchuk approved these changes

2022-07-20 08:13 UTC, merged