[SWE-1192][BOOKING MODULE] Connect slider and navigation points to ea…
senseteq-io/senseteq-booking-module pull request #31
Opened 2022-07-19 14:49 UTC by ArtemSuhoy

…ch other

2022-07-19 16:19 UTC, 5P4C3GR33D commented on src/app/components/elements/NavigationDots/NavigationDots.styled.js
> +    props.active &&
Only if property is not from constants. To constants there's no need to add this check.

2022-07-20 07:25 UTC, olenashevchuk requested changes

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/components/elements/NavigationDots/NavigationDots.js
> +  const screenSlidesArray = [...Array(numberScreenSlides)]
there is useless code

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/components/elements/NavigationDots/NavigationDots.js
>          <NavigationDotStyled
add key

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/components/elements/NavigationDots/NavigationDots.styled.js
> +    `}
there is excessive value

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/components/elements/NavigationDots/NavigationDots.styled.js
> +      background-color: var(--booking-module-neutral);
use mediator

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/hooks/ScreenSlider/useScreenSlider.js
> +
overcomplexity

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/hooks/ScreenSlider/useScreenSlider.js
> +  const handleNextScreenSlide = () => {
not according to standarts, why do you change this code?

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/hooks/ScreenSlider/useScreenSlider.js
> +  const handlePrevScreenSlide = () => {
same

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/hooks/ScreenSlider/useScreenSlider.js
> +  const handleInnerScreenSlide = (index) => {
same

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/hooks/ScreenSlider/useScreenSlider.js
> +  const handleInnerScreenSlide = (index) => {
not clearly function's name

2022-07-20 07:25 UTC, olenashevchuk commented on src/app/components/elements/NavigationDots/NavigationDots.styled.js
> +      height: 8px;
useless code

2022-07-20 09:04 UTC, olenashevchuk commented on src/app/components/elements/NavigationDots/NavigationDots.styled.js
> +  ${(props) => props?.active && isActiveDot}
use just conditions in styled.li

2022-07-20 09:05 UTC, olenashevchuk commented on src/app/hooks/ScreenSlider/useScreenSlider.js
> +  const handleDifferentScreenSlide = (index) =>
not a suitable name. think about what this function does

2022-07-20 10:02 UTC, olenashevchuk approved these changes

2022-07-20 10:03 UTC, merged